### ISSUE TITLE
Feedback on week 10 project progress for CS2113T-W17-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W17-4/main#118]
## Team progress for mid `v1.3`
* Milestone `v1.3` properly managed:
   * [x] A suitable deadline 2019-10-29 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-W17-4/main/issues/117 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/116 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/115 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/110 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/109 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/108 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/107 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/104 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/101 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/100 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/98 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/97 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/96 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/95 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/93 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/92 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/87 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/83 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/82 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/30 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/25 (:heavy_check_mark: well done!)
* [x] New JAR released on GitHub.(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
## Individual progress of @debbiextan for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/93 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/92 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/87 (:heavy_check_mark: well done!)
## Individual progress of @jasperosy for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/104 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/97 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/96 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/82 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/25 (:heavy_check_mark: well done!)
## Individual progress of @kahlokkee for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/117 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/116 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/115 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/110 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/109 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/108 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/107 (:heavy_check_mark: well done!)
## Individual progress of @kenlhc for mid `v1.3`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.3` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/101 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/100 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/98 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/95 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/83 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/30 (:heavy_check_mark: well done!)

Tutor: @jylee-git

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-23 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
