### ISSUE TITLE
Timeline for v1.4

### ISSUE THREAD

**Issue by kahlokkee** [AY1920S1-CS2113T-W17-4/main#177]
- [x] Mid `v1.4` ***Submission***: Week 12 Tuesday, 05/11/2019, 23:59 

### [***Internal***]  Post Mid `v1.4`:
- [x] Feature Freeze on Week 12 Wednesday, 06/11/2019
- [x] Test code merged by Week 12 Thursday, 07/11/2019, 18:00
- [x] UG Completion by Week 12 Thursday, 07/11/2019, 18:00
- [x] DG Completion by Week 12 Friday, 08/11/2019, 18:00
- [x] Final feature tweaking by Week 12 Saturday, 09/11/2019, 1800
- [x] Bug Testing from Week 12 Saturday, 09/11/2019

### Final submission (Week 13 Monday, 11/11/2019 23:59):
* [x] `v1.4` tag
* [x] UG
* [x] DG
* [x] .jar File
* [x] [***Individual***] PPP

**Comment by kahlokkee** [comment]
PANG GANG LO
