### ISSUE TITLE
Feedback on week 12 project progress for CS2113T-W17-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W17-4/main#183]
## Team progress for mid-`v1.4`
* Milestones setup:
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone `v1.4` properly managed:
   * [x] A suitable deadline 2019-11-11 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it e.g., https://github.com/AY1920S1-CS2113T-W17-4/main/issues/182 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/177 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/127 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/98 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/95 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/94 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/90 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/24 (:heavy_check_mark: well done!)
## Individual progress of @debbiextan for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/177 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/94 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/90 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @jasperosy for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/177 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/127 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/24 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @kahlokkee for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/182 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/177 (:heavy_check_mark: well done!)
* [x] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)
## Individual progress of @kenlhc for mid-`v1.4`
* [x] Merged updates to code (Java/FXML) files during the past 2 weeks (:heavy_check_mark: well done!)
* [x] Has issues assigned or PRs authored for `v1.4` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/177 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/98 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/95 (:heavy_check_mark: well done!)
* [ ] (not graded) Ensured the PPP file has links to your reposense report (:question: tick this yourself after completing the item)

Tutor: @jylee-git

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-11-06 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
