### ISSUE TITLE
Feedback on week 9 project progress for CS2113T-W17-4

### ISSUE THREAD

**Issue by nus-pe-script** [AY1920S1-CS2113T-W17-4/main#86]
## Team progress for `v1.2`
* [ ] Team PR created to the upstream repository with the title `[AY1920S1-CS2113T-W17-4] Contact List Pro`(:exclamation:)
* Milestone `v1.2` properly managed:
   * [x] A suitable deadline 2019-10-15 set(:heavy_check_mark: well done!)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-W17-4/main/issues/78 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/75 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/73 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/68 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/67 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/66 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/50 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/48 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/47 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/46 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/44 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/40 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/28 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/16 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/5 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/4 (:heavy_check_mark: well done!)
   * [x] All issues in this milestone are closed(:heavy_check_mark: well done!)
   * [x] Milestone explicitly closed(:heavy_check_mark: well done!)
   * [x] Code tagged as `v1.2`(:heavy_check_mark: well done!)
* Milestones setup:
   * [x] Milestone `v1.2` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.3` setup(:heavy_check_mark: well done!)
   * [x] Milestone `v1.4` setup(:heavy_check_mark: well done!)
* Milestone v1.3 planned:
   * [ ] A suitable deadline 2019-10-29 set(:exclamation:)
   * [x] Issues allocated to it https://github.com/AY1920S1-CS2113T-W17-4/main/issues/85 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/84 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/83 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/82 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/41 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/39 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/30 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/25 (:heavy_check_mark: well done!)
## Individual progress of @debbiextan for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/78 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/50 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/44 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/16 (:heavy_check_mark: well done!)
## Individual progress of @jasperosy for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/75 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/48 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/40 (:heavy_check_mark: well done!)
## Individual progress of @kahlokkee for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/68 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/67 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/66 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/4 (:heavy_check_mark: well done!)
## Individual progress of @kenlhc for `v1.2`
* [x] Merged updates to code (Java/FXML) files during the past week(:heavy_check_mark: well done!)
* [x] Has issues/PRs assigned for `v1.2` milestone https://github.com/AY1920S1-CS2113T-W17-4/main/issues/47 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/46 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/28 https://github.com/AY1920S1-CS2113T-W17-4/main/issues/5 (:heavy_check_mark: well done!)

Tutor: @jylee-git

Please reply in this thread if there are any inaccuracies in the above observations.

 <sub> Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-10-16 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.</sub>
